name: CI

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # This step checks out your repository's code

    - name: Create reports directory
      run: mkdir reports

    - name: JMeter Test
      uses: QAInsights/PerfAction@v5.6.2
      with:
        test-plan-path: ./Test_Plan.jmx  # Corrected path to your JMX file
        args: "-e -o ./reports/html/"

    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results
        path: result.jtl
        if-no-files-found: error

  
